services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: booltan
      POSTGRES_PASSWORD: booltan
      POSTGRES_DB: booltan
    ports:
      - "5432:5432"
    volumes:
      - booltan_pgdata:/var/lib/postgresql/data

volumes:
  booltan_pgdata:
